let musicDB = [
  {
    id: 0,
    name: "Shakedown",
    author_name: "Clarx",
    img: "shakedown.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Clarx - Shakedown [NCS Release].mp3",
    attribution: {
      song: "Clarx - Shakedown [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "http://youtu.be/qJT0mc3q6Lg",
    },
  },
  {
    id: 1,
    name: "Games Worldbeat",
    author_name: "Bernardo R.",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "mixkit-games-worldbeat-466.mp3",
    attribution: {
      song: "Games Worldbeat",
      musicBy: "mixkit",
      download: null,
      stream: "",
    },
  },
  {
    id: 2,
    name: "OverMyHead",
    author_name: " ROY KNOX",
    img: "over-my-head-1602154826-mOiKzOJDe6.jpg",
    lang: "ENGLISH",
    type: "electronic",
    timesPlayed: 0,
    musicName: "ROY KNOX -  Over My Head (Feat. Mike Robert) [NCS Release].mp3",
    attribution: {
      song: "ROY KNOX - Over My Head (Feat. Mike Robert) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "",
    },
  },
  {
    id: 3,
    name: "Want You (feat. Sara Skinner)",
    author_name: "Subtact, Sara Skinner",
    img: "want-you-feat-sara-skinner-1586956276-s4lOrfrHQj.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Subtact - Want You (feat. Sara Skinner) [NCS Release].mp3",
    attribution: {
      song: "Subtact - Want You (feat. Sara Skinner) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "http://youtu.be/Pww31vN_1QY",
    },
  },
  {
    id: 4,
    name: "Apocalypse",
    author_name: "Midranger",
    img: "apocalypse-1600776027-tsCmgK4gEU.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Midranger - Apocalypse [NCS Release].mp3",
    attribution: {
      song: "Midranger - Apocalypse [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "http://youtu.be/Whw1sWDpAvE",
    },
  },
  {
    id: 5,
    name: "Alive",
    author_name: "Neoni, N3WPORT",
    img: "alive.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "N3WPORT - Alive (feat. Neoni) [NCS Release].mp3",
    attribution: {
      song: "N3WPORT - Alive (feat. Neoni) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "http://youtu.be/vJAcXd_UtWQ",
    },
  },
  {
    id: 6,
    name: "Impact Moderato",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: "",
    },
  },
  {
    id: 7,
    name: "Impact Moderato 2",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact2.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: "",
    },
  },
  {
    id: 8,
    name: "Ignite",
    author_name: "Tom wilson, Heuse",
    img: "ignite-1600419626-nHn4WXY79q.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Heuse & Tom Wilson - Ignite [NCS Release].mp3",
    attribution: {
      song: "Heuse & Tom Wilson - Ignite [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: null,
      stream: "http://youtu.be/zbqgv0mMfwk",
    },
  },
  {
    id: 9,
    name: "On My Way",
    author_name: "Alan Walker",
    img: "1.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "1.mp3",
    attribution: {
      song: "Alan Walker - On My Way",
      musicBy: "Alan Walker",
      download: null,
      stream: "https://youtu.be/dhYOPzcsbGM",
    },
  },
  {
    id: 10,
    name: "Alan Walker-Fade",
    author_name: "Alan Walker",
    img: "2.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "2.mp3",
    attribution: {
      song: "Alan Walker-Fade",
      musicBy: "Alan Walker",
      download: null,
      stream: "https://youtu.be/60ItHLz5WEA",
    },
  },
  {
    id: 11,
    name: "Cartoon-on & on",
    author_name: "Deniel Levi ",
    img: "3.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "3.mp3",
    attribution: {
      song: "Deniel Levi - Cartoon-on & on",
      musicBy: "Deniel Levi",
      download: null,
      stream: "https://youtu.be/K4DyBUG242c",
    },
  },
  {
    id: 12,
    name: "Warriyo - Mortals",
    author_name: "Mortals",
    img: "4.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "4.mp3",
    attribution: {
      song: "Mortals - Warriyo - Mortals",
      musicBy: "Mortals",
      download: null,
      stream: "https://youtu.be/yJg-Y5byMMw",
    },
  },
  {
    id: 13,
    name: "Ertugrul Gazi",
    author_name: "Ertugrul",
    img: "5.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "5.mp3",
    attribution: {
      song: "Ertugrul Gazi",
      musicBy: "Ertugrul",
      download: null,
      stream: "",
    },
  },
  {
    id: 14,
    name: "Electronic Music",
    author_name: "Electro",
    img: "6.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "6.mp3",
    attribution: {
      song: "Electronic Music",
      musicBy: "Electro",
      download: null,
      stream: "",
    },
  },
  {
    id: 15,
    name: "Agar Tum Sath Ho",
    author_name: "Tamashaa",
    img: "7.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "7.mp3",
    attribution: {
      song: "Agar Tum Sath Ho",
      musicBy: "Tamashaa",
      download: null,
      stream: "https://youtu.be/sK7riqg2mr4",
    },
  },
  {
    id: 16,
    name: "Suna Hai",
    author_name: "Neha Kakker",
    img: "8.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "8.mp3",
    attribution: {
      song: "Suna Hai",
      musicBy: "Neha Kakker",
      download: null,
      stream: "https://youtu.be/bpa_gH1h0w4",
    },
  },
  {
    id: 17,
    name: "Dilbar",
    author_name: "Satyameva Jayate",
    img: "9.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "9.mp3",
    attribution: {
      song: "Dilbar",
      musicBy: "Satyameva Jayate",
      download: null,
      stream: "https://youtu.be/JFcgOboQZ08",
    },
  },
  {
    id: 18,
    name: "Duniya",
    author_name: "Luka Chupi",
    img: "10.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "10.mp3",
    attribution: {
      song: "Duniya",
      musicBy: "Luka Chupi",
      download: null,
      stream: "https://youtu.be/hVCYwwFwGEE",
    },
  },
  {
    id: 19,
    name: "Lagdi Lahore Di",
    author_name: "Street Dancer 3D",
    img: "11.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "11.mp3",
    attribution: {
      song: "Lagdi Lahore Di",
      musicBy: "Street Dancer 3D",
      download: null,
      stream: "https://youtu.be/1QXyLrKnQrg",
    },
  },
  {
    id: 20,
    name: "Putt Jatt Da",
    author_name: "Putt Jatt Da",
    img: "12.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "12.mp3",
    attribution: {
      song: "Putt Jatt Da",
      musicBy: "Putt Jatt Da",
      download: null,
      stream: "https://youtu.be/MVXjxl6_0MM",
    },
  },
  {
    id: 21,
    name: "Baarishein",
    author_name: "Atif Aslam",
    img: "13.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "13.mp3",
    attribution: {
      song: "Baarishein",
      musicBy: "Atif Aslam",
      download: null,
      stream: "https://youtu.be/P0NfnFYpENo",
    },
  },
  {
    id: 22,
    name: "Vaaste",
    author_name: "Dhvani Bhanushali",
    img: "14.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "14.mp3",
    attribution: {
      song: "Vaaste",
      musicBy: "Dhvani Bhanushali",
      download: null,
      stream: "https://youtu.be/hccVM73LXa0",
    },
  },
  {
    id: 23,
    name: "Lut Gaye",
    author_name: "Jubin Nautiyal",
    img: "15.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "15.mp3",
    attribution: {
      song: "Lut Gaye",
      musicBy: "Jubin Nautiyal",
      download: null,
      stream: "https://youtu.be/sCbbMZ-q4-I",
    },
  },
  {
    id: 24,
    name: "Tu Meri Jindagi",
    author_name: "Jubin Nautiyal",
    img: "16.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "16.mp3",
    attribution: {
      song: "Tu Meri Jindagi ",
      musicBy: "Jubin Nautiyal",
      download: null,
      stream: "https://youtu.be/VYslt8bc-4Q",
    },
  },
  {
    id: 25,
    name: "Batao Yaad Hai Tu",
    author_name: "Rahat Fateh Ali Khan",
    img: "17.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "17.mp3",
    attribution: {
      song: "Batao Yaad Hai Tu",
      musicBy: "Rahat Fateh Ali Khan",
      download: null,
      stream: "https://youtu.be/6-n_szx2XRE",
    },
  },
  {
    id: 26,
    name: "Mere Dhol Judai",
    author_name: "Ali Sethi Seha Gill",
    img: "18.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "18.mp3",
    attribution: {
      song: "Mere Dhol Judai",
      musicBy: "Ali Sethi Seha Gill",
      download: null,
      stream: "https://youtu.be/g8VBT8GbwZc",
    },
  },

  {
    id: 27,
    name: "Eh Munde Pagal N",
    author_name: "Ap Dhillon , Gurinder",
    img: "19.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "19.mp3",
    attribution: {
      song: "Eh Munde Pagal N",
      musicBy: "Ap Dhillon , Gurinder",
      download: null,
      stream: "https://youtu.be/rmEK0-vRVdc",
    },
  },
  {
    id: 28,
    name: "Naina ashq na ho",
    author_name: "Arjit Singh",
    img: "A1.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "A1.mp3",
    attribution: {
      song: "Naina ashq na ho",
      musicBy: "Arjit Singh",
      download: null,
      stream: "https://youtu.be/yLI2k4Ffc8M",
    },
  },
  {
    id: 29,
    name: "Khairiyat",
    author_name: "Arjit Singh",
    img: "A2.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "A2.mp3",
    attribution: {
      song: "Khairiyat",
      musicBy: "Arjit Singh",
      download: null,
      stream: "https://youtu.be/m6jiyLhXkj8",
    },
  },
];

export default musicDB;
